/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carpetaProyectoEx;

import creacion.leerArchivo;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roc53
 */
public class Mostrar extends javax.swing.JInternalFrame {

    DefaultTableModel C_Tabla = new DefaultTableModel();
    private int reng = -1;
    private String codigoEncontrado = "";

    /**
     * Creates new form NewJInternalFrame
     */
    public Mostrar() throws IOException {
        initComponents();
        setClosable(true);//agregamos boton para cerrar
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);//cerrar mejor que this.hide
        
         String[] titulos = {"Codigo", "Nombre", "Correro", "Telefono", "Edad"};
        C_Tabla = new DefaultTableModel(null, titulos);
        Tabla.setModel(C_Tabla);
        LeerArch();//en clase los es cargar archivo
    }
   

    public void LeerArch() throws IOException {
        //le dices a tu tabla que muestre lo que hay en el contenedor
       
        try {
            BufferedReader leer = new BufferedReader(new FileReader("agenda.txt"));
          
            String renglon = "";
            //String auxiliar = "";
            while ((renglon = leer.readLine()) != null) {//busca datos renglon por renglon hasta  que se acaben
                //auxiliar += renglon + "\n";//guardo los datos que salen en auxiliar
                String[] datos = renglon.split(" _ ");//se sepaa en arreglos 
                String co = datos[0];
                String nom = datos[1];
                String correo = datos[2];
                String tel = datos[3];
                String edad = datos[4];

                C_Tabla.addRow(new Object[]{co, nom, correo, tel, edad});
                Tabla.setModel(C_Tabla);
            }
            leer.close();
            //JOptionPane.showMessageDialog(null,auxiliar); //nuestro los datos encontrados 👀

        } catch (FileNotFoundException ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();

        jPanel1.setPreferredSize(new java.awt.Dimension(10, 78));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(394, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminar);

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel3.add(btnModificar);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7);

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        jPanel4.add(jScrollPane1);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(394, 10));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
         if (reng == -1) {
            JOptionPane.showMessageDialog(null, "Ellije una fila");
        } else {
            BufferedReader leer = null;
            try {

                JOptionPane.showMessageDialog(null, codigoEncontrado);
                FileWriter archivoA = new FileWriter("auxiliar.txt");
                leer = new BufferedReader(new FileReader("agenda.txt"));
                String renglon = "";
                String auxiliar = "";
                while ((renglon = leer.readLine()) != null) {//busca datos renglon por renglon hasta  🔍
                   
                    if ((renglon.length()) != 0) {
                        JOptionPane.showMessageDialog(null, renglon.length(),"Longitud de renglon",JOptionPane.INFORMATION_MESSAGE);
                        String[] partes = renglon.split(" _ ");
                        
                        if (codigoEncontrado.equals(partes[0])) {
                            
                            String co = JOptionPane.showInputDialog("Escribe el codigo");
                            String nom = JOptionPane.showInputDialog("Escribe el nombre");
                            String corr = JOptionPane.showInputDialog("Escribe el correo");
                            String tel = JOptionPane.showInputDialog("Escribe el telefono");
                            String edad = JOptionPane.showInputDialog("Escribe la edad");
                            nom = nom.toUpperCase();
                            corr = corr.toLowerCase();
                            archivoA.write(co+" _ "+nom+" _ "+corr+" _ "+tel+" _ "+edad+"\n");
                            
                            
                        }else{
                            
                               
                               archivoA.write(renglon+"\n");
                        }
                        }
                }
                            archivoA.close(); //cierro archivo
                            leer.close();
                            
                            File arg = new File("agenda.txt");
                            File arg2 = new File ("auxiliar.txt");
                            Path original = Paths.get("auxiliar.txt");
                            Path modificar = Paths.get("agenda.txt");
                            if (arg.exists()&& arg2.exists()){
                            //arg.delete();
                            Files.move(original,modificar,StandardCopyOption.REPLACE_EXISTING);
                            
                            }
                 
            } catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } 

        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_TablaMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        if (reng == -1) {
            JOptionPane.showMessageDialog(null, "Ellije una fila");
        } else {
            BufferedReader leer = null;
            try {

                JOptionPane.showMessageDialog(null, codigoEncontrado);
                FileWriter archivoA = new FileWriter("auxiliar.txt");
                leer = new BufferedReader(new FileReader("agenda.txt"));
                String renglon = "";
                String auxiliar = "";
                while ((renglon = leer.readLine()) != null) {//busca datos renglon por renglon hasta  🔍
                    // auxiliar += renglon + "\n";//guardo los datos que salen en auxiliar
                    if ((renglon.length()) != 0) {
                        JOptionPane.showMessageDialog(null, renglon.length(),"Longitud de renglon",JOptionPane.INFORMATION_MESSAGE);
                        String[] partes = renglon.split(" _ ");
                        
                        if (codigoEncontrado.equals(partes[0])) {
                            
                           
                        }else{
                            
                                
                               archivoA.write(renglon+"\n");// se agregan los datos del renglon sin modificar(antes de separarlos)
                        }
                        }
                }
                            archivoA.close(); //cierro archivo
                            leer.close();
                            
                            File arg = new File("agenda.txt");
                            File arg2 = new File ("auxiliar.txt");
                            Path original = Paths.get("auxiliar.txt");
                            Path modificar = Paths.get("agenda.txt");
                            if (arg.exists()&& arg2.exists()){
                            //arg.delete();
                            Files.move(original,modificar,StandardCopyOption.REPLACE_EXISTING);
                            
                            }
                            
            } catch (FileNotFoundException ex) {
                java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IOException ex) {
                java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } 

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void TablaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMousePressed

        // TODO add your handling code here:
        //se coloca en elmaus present porque se activa con solo colocar el maus arriba
        reng = Tabla.getSelectedRow();
        //JOptionPane.showMessageDialog(null, reng);
        if (reng == -1) {
            JOptionPane.showMessageDialog(null, "Elije una fila");
        } else {
            Tabla.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    codigoEncontrado = Tabla.getValueAt(reng, 0).toString();

                }
            });
        }

    }//GEN-LAST:event_TablaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
