/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carpetaProyectoEx;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author roc53
 */
public class Principal extends javax.swing.JFrame {

    public boolean VenatanaCrear = false;
   private Mostrar mostrar;
   private crear crear;
   
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuACrear = new javax.swing.JMenu();
        mnuAc = new javax.swing.JMenuItem();
        mnuAMostrar = new javax.swing.JMenuItem();
        mnuASalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuACrear.setMnemonic('f');
        mnuACrear.setText("Archivo");

        mnuAc.setMnemonic('o');
        mnuAc.setText("Crear Archivo");
        mnuAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcActionPerformed(evt);
            }
        });
        mnuACrear.add(mnuAc);

        mnuAMostrar.setMnemonic('s');
        mnuAMostrar.setText("Mostrar datos del Archivo");
        mnuAMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAMostrarActionPerformed(evt);
            }
        });
        mnuACrear.add(mnuAMostrar);

        mnuASalir.setMnemonic('x');
        mnuASalir.setText("Salir");
        mnuASalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuASalirActionPerformed(evt);
            }
        });
        mnuACrear.add(mnuASalir);

        menuBar.add(mnuACrear);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuASalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuASalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuASalirActionPerformed
public boolean estadoV(boolean est){
    boolean estadoF= false;
    estadoF = est;
return estadoF;

}
    private void mnuAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "Estado antes de acceder: "+VenatanaCrear);
        if (crear == null || crear.isClosed()){
             crear = new crear();
            Escritorio.add(crear);//la agragamos al escritorio
            crear.setVisible(true);
        }else {
            try {
                crear.setSelected(true);//como si existe
                crear.toFront();//traemos la ventana a frene 
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
           
        
        
       
    }//GEN-LAST:event_mnuAcActionPerformed

    private void mnuAMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAMostrarActionPerformed
        try {
            // TODO add your handling code here:
           
            if (mostrar == null||mostrar.isClosed()){
                mostrar  = new Mostrar();
                Escritorio.add(mostrar);
                mostrar.setVisible(true);
            }else{
                try {
                    mostrar.setSelected(true);
                    mostrar.toFront();
                } catch (Exception e) {
                    e.printStackTrace();

                }
            }
             
            
            
            
           
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuAMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuACrear;
    private javax.swing.JMenuItem mnuAMostrar;
    private javax.swing.JMenuItem mnuASalir;
    private javax.swing.JMenuItem mnuAc;
    // End of variables declaration//GEN-END:variables

}
