/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Examen2;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roc53
 */
public class V_Agregar extends javax.swing.JInternalFrame {
    DefaultTableModel M_Ctabla =  new DefaultTableModel();
    

    /**
     * Creates new form V_Agregar
     */
    public V_Agregar() throws IOException {
        initComponents();
        setClosable(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        CargarTabla();
        Datos();
        Codigo();
        LeerArchivos();
       
    }
private void CargarTabla(){
        String []titulos = {"codigo","nombre","edad", "correo"};
        M_Ctabla = new DefaultTableModel(null, titulos);
        Tabla.setModel(M_Ctabla);
}
private void Codigo() {
        try {

            //aqui no sirve "setLocationRelativeTo"
            FileWriter archivo = new FileWriter("Codigo.txt", true);
            archivo.close();
        } catch (IOException ex) {
            Logger.getLogger(V_Agregar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void Datos() {
        try {

            //aqui no sirve "setLocationRelativeTo"
            FileWriter archivo = new FileWriter("Datos.txt", true);
            archivo.close();
        } catch (IOException ex) {
            Logger.getLogger(V_Agregar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void LeerArchivos() throws IOException {
        //le dices a tu tabla que muestre lo que hay en el contenedor

        try {
            BufferedReader leer = new BufferedReader(new FileReader("Datos.txt"));
            BufferedReader leerC = new BufferedReader(new FileReader("Codigo.txt"));

            String renglon = "";
            String renglonC = "";
           
            while (((renglon = leer.readLine()) != null&& ((renglonC = leerC.readLine()) != null))) {//busca datos renglon por renglon hasta  que se acaben
                //auxiliar += renglon + "\n";//guardo los datos que salen en auxiliar
                String []aDatos = renglon.split(" _ ");
                String []aCodigo = renglonC.split(" _ ");
                
                if (aDatos[0]==aCodigo[0]){
                 M_Ctabla.addRow(new Object[]{aCodigo[0],aDatos[1],aDatos[2],aDatos[3]});
                Tabla.setModel(M_Ctabla);
                }
            }
            leer.close();
            leerC.close();
            //JOptionPane.showMessageDialog(null,auxiliar); //nuestro los datos encontrados 👀

        } catch (FileNotFoundException ex) {

        }
    }
   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnCodigo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();

        jPanel2.setPreferredSize(new java.awt.Dimension(414, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(10, 10));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2));

        jPanel6.setLayout(new java.awt.GridLayout(8, 1));

        jLabel1.setText("Nombre");
        jPanel6.add(jLabel1);

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel6.add(txtNombre);

        jLabel2.setText("Edad");
        jPanel6.add(jLabel2);

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        jPanel6.add(txtEdad);

        jLabel3.setText("Correo ");
        jPanel6.add(jLabel3);

        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        jPanel6.add(txtCorreo);

        btnCodigo.setText("Generar Codigo");
        btnCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodigoActionPerformed(evt);
            }
        });
        jPanel6.add(btnCodigo);

        btnAgregar.setText("Agregar");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel6.add(btnAgregar);

        jPanel4.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        jPanel7.add(jScrollPane1);

        jPanel4.add(jPanel7);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(414, 10));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        int caracter = evt.getKeyChar();
        if (caracter >= 65 && caracter <= 90 || caracter == 8){
            
        
        }else{
        evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        // TODO add your handling code here:
        int caracter = evt.getKeyChar();
        if (caracter >= 48 && caracter <= 57 || caracter == 8){
            
        
        }else{
        evt.consume();
        }
    }//GEN-LAST:event_txtEdadKeyTyped

   
    
    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        // TODO add your handling code here:
        int caracter = evt.getKeyChar();
        if (caracter >= 97 && caracter <= 122 
                ||caracter >= 48 && caracter <= 57 || caracter == 8 
                ||caracter == 64 || caracter == 46 ){
              
            
            
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void btnCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodigoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Area 1");
        String nombre = txtNombre.getText();
        String edad = txtEdad.getText();
        String correo = txtCorreo.getText();
       
        
       if (nombre.length() != 0 && edad.length() != 0 && correo.length()!=0){
         if (edad.length()>2){
            JOptionPane.showMessageDialog(null, "Edad no valida");
            txtEdad.setText("");
        }else{
         JOptionPane.showMessageDialog(null, "Accedido");
        String codigo = (nombre.substring(0,2)+edad.substring(0,2));
        btnAgregar.setEnabled(true);
        JOptionPane.showMessageDialog(null, "Su codigo es: "+codigo);
        txtCorreo.setEnabled(false);
        txtEdad.setEnabled(false);
        txtNombre.setEnabled(false);
               
         }
        
        
        }else{
           JOptionPane.showMessageDialog(null, "Faltan datos ");
       }
        
    }//GEN-LAST:event_btnCodigoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
         String nombre = txtNombre.getText();
        String edad = txtEdad.getText();
        String correo = txtCorreo.getText();
        String codigo = (nombre.substring(0,2)+edad.substring(0,2));
        FileWriter archivo = null;
        try {
            archivo = new FileWriter("Codigo.txt", true);
            archivo.write(codigo +" _ "+nombre+"\n");
            archivo.close();
            JOptionPane.showMessageDialog(null, "Registro guardado");
            archivo = new FileWriter("Datos.txt", true);
            archivo.write(codigo +" _ "+nombre+" _ "+edad+" _ "+correo+"\n");
            archivo.close();
            JOptionPane.showMessageDialog(null, "Registro guardado");
            
            M_Ctabla.addRow(new Object[]{codigo,nombre,edad,correo});//se ingresan los datos al contenedor
            Tabla.setModel(M_Ctabla);

        } catch (IOException ex) {
            Logger.getLogger(V_Agregar.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                archivo.close();
            } catch (IOException ex) {
                Logger.getLogger(V_Agregar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        txtCorreo.setText("");
        txtEdad.setText("");
        txtNombre.setText("");
        txtCorreo.setEnabled(true);
        txtEdad.setEnabled(true);
        txtNombre.setEnabled(true);
        btnAgregar.setEnabled(false);
    
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
