/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

/**
 *
 * @author roc53
 */
public class BuscarVocales extends javax.swing.JFrame {

    /**
     * Creates new form BuscarVocales
     */
    public BuscarVocales() {
        initComponents();
        setLocationRelativeTo(null);//centra la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        optA = new javax.swing.JRadioButton();
        optE = new javax.swing.JRadioButton();
        optI = new javax.swing.JRadioButton();
        optO = new javax.swing.JRadioButton();
        optU = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPalabra = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lbnLetra = new javax.swing.JLabel();
        lbnCantidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 200));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(10, 270));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 15));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(120, 270));
        jPanel3.setLayout(new java.awt.GridLayout(5, 1));

        buttonGroup1.add(optA);
        optA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        optA.setSelected(true);
        optA.setText("Buscar A");
        optA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAActionPerformed(evt);
            }
        });
        jPanel3.add(optA);

        buttonGroup1.add(optE);
        optE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        optE.setText("Buscar E");
        jPanel3.add(optE);

        buttonGroup1.add(optI);
        optI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        optI.setText("Buscar I");
        jPanel3.add(optI);

        buttonGroup1.add(optO);
        optO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        optO.setText("Buscar O");
        jPanel3.add(optO);

        buttonGroup1.add(optU);
        optU.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        optU.setText("Buscar U");
        jPanel3.add(optU);

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(400, 15));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Escribe la palabra");
        jPanel5.add(jLabel1);

        txtPalabra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPalabraActionPerformed(evt);
            }
        });
        jPanel5.add(txtPalabra);

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel5.add(btnBuscar);

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setText("salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel5.add(btnSalir);

        lbnLetra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel5.add(lbnLetra);

        lbnCantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel5.add(lbnCantidad);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void optAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optAActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Operacion op = new Operacion();

        String cad = txtPalabra.getText();
        int c = 0;
        cad = cad.trim();//elimina los espacios en blanco al principo y final de la cadena

        if (cad.equals("")) {
            lbnCantidad.setText("");
            lbnLetra.setText("Canpo basio");
        } else {
            if (optA.isSelected()) {
                c = op.buscarA(cad);
                lbnLetra.setText("El numero de A es: ");
                lbnCantidad.setText(Integer.toString(c));
            }  
            if (optE.isSelected()) {
                c = op.BuscarE(cad);
                lbnLetra.setText("El numero de E es: ");
                lbnCantidad.setText(Integer.toString(c));
            }  
            if (optI.isSelected()) {
                c = op.BuscarI(cad);
                lbnLetra.setText("El numero de I es: ");
                lbnCantidad.setText(Integer.toString(c));
            }  
            if (optO.isSelected()) {
                c = op.BuscarO(cad);
                lbnLetra.setText("El numero de O es: ");
                lbnCantidad.setText(Integer.toString(c));
            } 
            if (optU.isSelected()) {
                c = op.BuscarU(cad);
                lbnLetra.setText("El numero de U es: ");
                lbnCantidad.setText(Integer.toString(c));
            }
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPalabraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPalabraActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarVocales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarVocales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbnCantidad;
    private javax.swing.JLabel lbnLetra;
    private javax.swing.JRadioButton optA;
    private javax.swing.JRadioButton optE;
    private javax.swing.JRadioButton optI;
    private javax.swing.JRadioButton optO;
    private javax.swing.JRadioButton optU;
    private javax.swing.JTextField txtPalabra;
    // End of variables declaration//GEN-END:variables
}
