/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Clases;

import javax.swing.JOptionPane;

/**
 *
 * @author roc53
 */
public class Productos extends javax.swing.JFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbnTipo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbnDescripcion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbnUnidades = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lbnPresio = new javax.swing.JLabel();
        txtPresio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lbnSubTotal = new javax.swing.JLabel();
        lbnSubTotal1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        cbxCategorias = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        cbxCarnes = new javax.swing.JComboBox<>();
        cbxAbarrotes = new javax.swing.JComboBox<>();
        cbxCarnesFrias = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        cbxDescuentos = new javax.swing.JComboBox<>();
        cbxIva = new javax.swing.JComboBox<>();
        cbxUnidades = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAAgregar = new javax.swing.JMenuItem();
        mnuAComprar = new javax.swing.JMenuItem();
        mnuASalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tiendita ");

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel12.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tipo de prodructos");
        jPanel12.add(jLabel1);

        lbnTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbnTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel12.add(lbnTipo);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Descripcion de producto");
        jPanel12.add(jLabel3);

        lbnDescripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbnDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel12.add(lbnDescripcion);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Descuentos o unidades");
        jPanel12.add(jLabel5);

        lbnUnidades.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbnUnidades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel12.add(lbnUnidades);

        jPanel1.add(jPanel12);

        jPanel11.setLayout(new java.awt.GridLayout(3, 2));

        lbnPresio.setText("Presio");
        jPanel11.add(lbnPresio);

        txtPresio.setEnabled(false);
        txtPresio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPresioKeyTyped(evt);
            }
        });
        jPanel11.add(txtPresio);

        jLabel2.setText("Unidad o peso");
        jPanel11.add(jLabel2);

        txtPeso.setEnabled(false);
        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });
        txtPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesoKeyTyped(evt);
            }
        });
        jPanel11.add(txtPeso);

        lbnSubTotal.setText("SubTotal ");
        jPanel11.add(lbnSubTotal);
        jPanel11.add(lbnSubTotal1);

        jPanel1.add(jPanel11);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(420, 150));
        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        jPanel8.setLayout(new java.awt.GridLayout(3, 1));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9);

        cbxCategorias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un producto", "Carnes", "Abarrotes", "Carnes Firas" }));
        cbxCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriasActionPerformed(evt);
            }
        });
        jPanel8.add(cbxCategorias);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel10);

        jPanel2.add(jPanel8);

        jPanel6.setLayout(new java.awt.GridLayout(3, 1));

        cbxCarnes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxCarnes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Res", "Puerco", "Pollo", "Pescado" }));
        cbxCarnes.setEnabled(false);
        cbxCarnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCarnesActionPerformed(evt);
            }
        });
        jPanel6.add(cbxCarnes);

        cbxAbarrotes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxAbarrotes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azucar", "Sal", "Arina", "Huevo", "Otros" }));
        cbxAbarrotes.setEnabled(false);
        jPanel6.add(cbxAbarrotes);

        cbxCarnesFrias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxCarnesFrias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jamon", "Salchicha", "Queso de puerco", "Chuleta" }));
        cbxCarnesFrias.setEnabled(false);
        jPanel6.add(cbxCarnesFrias);

        jPanel2.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(3, 1));

        cbxDescuentos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxDescuentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5%", "10%", "15%" }));
        cbxDescuentos.setEnabled(false);
        cbxDescuentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDescuentosActionPerformed(evt);
            }
        });
        jPanel7.add(cbxDescuentos);

        cbxIva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxIva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12%", "16%", "20%" }));
        cbxIva.setEnabled(false);
        cbxIva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxIvaActionPerformed(evt);
            }
        });
        jPanel7.add(cbxIva);

        cbxUnidades.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxUnidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pieza", "Kilo", "Gramos" }));
        cbxUnidades.setEnabled(false);
        jPanel7.add(cbxUnidades);

        jPanel2.add(jPanel7);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(420, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel3.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel5.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        jMenu1.setText("Archivo");

        mnuAAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuAAgregar.setText("Agregar");
        mnuAAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAAgregar);

        mnuAComprar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuAComprar.setText("Comprar");
        mnuAComprar.setEnabled(false);
        mnuAComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAComprarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAComprar);

        mnuASalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mnuASalir.setText("Salir");
        mnuASalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuASalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuASalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriasActionPerformed
        // TODO add your handling code here: //Carnes, Abarrotes, Carnes Firas
        
       // JOptionPane.showMessageDialog(null, cbxCategorias);
       if (cbxCategorias.getSelectedItem()==("Elige un producto")){
       
            cbxCarnes.setEnabled(false);
            cbxAbarrotes.setEnabled(false);
            cbxCarnesFrias.setEnabled(false);
            cbxDescuentos.setEnabled(false);
            cbxIva.setEnabled(false);
            cbxUnidades.setEnabled(false);
       }
        if (cbxCategorias.getSelectedItem()=="Carnes"){
            cbxCarnes.setEnabled(true);
            cbxAbarrotes.setEnabled(false);
            cbxCarnesFrias.setEnabled(false);
            cbxDescuentos.setEnabled(true);
            cbxIva.setEnabled(false);
            cbxUnidades.setEnabled(false);
        }
        if (cbxCategorias.getSelectedItem()=="Abarrotes"){
            cbxCarnes.setEnabled(false);
            cbxAbarrotes.setEnabled(true);
            cbxCarnesFrias.setEnabled(false);
             cbxDescuentos.setEnabled(false);
            cbxIva.setEnabled(true);
            cbxUnidades.setEnabled(false);
        }
        if (cbxCategorias.getSelectedItem()=="Carnes Firas"){
            cbxCarnes.setEnabled(false);
            cbxAbarrotes.setEnabled(false);
            cbxCarnesFrias.setEnabled(true);
             cbxDescuentos.setEnabled(false);
            cbxIva.setEnabled(false);
            cbxUnidades.setEnabled(true);
        }
    }//GEN-LAST:event_cbxCategoriasActionPerformed

    private void cbxCarnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCarnesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCarnesActionPerformed

    private void cbxDescuentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDescuentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDescuentosActionPerformed

    private void cbxIvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxIvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxIvaActionPerformed

    private void mnuAComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAComprarActionPerformed
        // TODO add your handling code here:
        if (txtPresio.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(null, "Escribe el presio del producto");
        }else{
        if (cbxCategorias.getSelectedItem()=="Carnes"){
            String descuento = (String)cbxDescuentos.getSelectedItem();
            float des = Float.parseFloat(descuento.substring(0, descuento.length()-1));
            int presio = Integer.parseInt(txtPresio.getText());
            float total = presio - (presio * (des/100));
            lbnSubTotal1.setText(Float.toString(total));  
        }
        if (cbxCategorias.getSelectedItem()=="Abarrotes"){
            String impuesto = (String)cbxIva.getSelectedItem();
            float iva = Float.parseFloat(impuesto.substring(0, impuesto.length()-1));
            int presio = Integer.parseInt(txtPresio.getText());
            float total = presio + (presio * (iva/100));
            lbnSubTotal1.setText(Float.toString(total));  
        }
        if (cbxCategorias.getSelectedItem()=="Carnes Firas"){
            if (txtPeso.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Agrega una cantidad o peso al producto ");
            }else{
                //String descuento = (String)cbxUnidades.getSelectedItem();
                float presio = Float.parseFloat(txtPresio.getText());
                float peso = Float.parseFloat(txtPeso.getText());
                float total = presio * (peso);
                lbnSubTotal1.setText(Float.toString(total));
            }
            
        }
        }
        
    }//GEN-LAST:event_mnuAComprarActionPerformed

    private void mnuASalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuASalirActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_mnuASalirActionPerformed

    private void mnuAAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAAgregarActionPerformed
        // TODO add your handling code here:
        if (cbxCategorias.getSelectedItem()== "Elige un producto"){
            JOptionPane.showMessageDialog(null, "Elige una opcion de la categoria");
        }else{
        if (cbxCategorias.getSelectedItem()=="Carnes"){
            String tipo = (String)cbxCategorias.getSelectedItem();
            lbnTipo.setText(tipo);
            String carnes = (String)cbxCarnes.getSelectedItem();
            lbnDescripcion.setText(carnes);
            String descuentos = (String)cbxDescuentos.getSelectedItem();
            lbnUnidades.setText(descuentos);
            mnuAAgregar.setEnabled(false);
            mnuAComprar.setEnabled(true);
            txtPresio.setEnabled(true);
        }
         if (cbxCategorias.getSelectedItem()=="Abarrotes"){
            String tipo = (String)cbxCategorias.getSelectedItem();
            lbnTipo.setText(tipo);
            String abarrotes = (String)cbxAbarrotes.getSelectedItem();
            lbnDescripcion.setText(abarrotes);
            String iva = (String)cbxIva.getSelectedItem();
            lbnUnidades.setText(iva);
            mnuAAgregar.setEnabled(false);
            mnuAComprar.setEnabled(true);
            txtPresio.setEnabled(true);
        }
         if (cbxCategorias.getSelectedItem()=="Carnes Firas"){
            String tipo = (String)cbxCategorias.getSelectedItem();
            lbnTipo.setText(tipo);
            String carFria = (String)cbxCarnesFrias.getSelectedItem();
            lbnDescripcion.setText(carFria);
            String unidad = (String)cbxUnidades.getSelectedItem();
            lbnUnidades.setText(unidad);
            mnuAAgregar.setEnabled(false);
            mnuAComprar.setEnabled(true);
           txtPresio.setEnabled(true);
           txtPeso.setEnabled(true);
        }
        
        }
        
        
        
         
        
        
    }//GEN-LAST:event_mnuAAgregarActionPerformed

    private void txtPresioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPresioKeyTyped
        // TODO add your handling code here:
       int numero = evt.getKeyChar(); //optengo el codigo ascci del carcter que se esta ingresando
       if (numero >= 48 && numero <= 57 || numero == 8){
       
       }else{
           evt.consume();
           JOptionPane.showMessageDialog(null, "Dato no valido");
       }
       
    }//GEN-LAST:event_txtPresioKeyTyped

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void txtPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesoKeyTyped
        // TODO add your handling code here:
        int numero = evt.getKeyChar(); //optengo el codigo ascci del carcter que se esta ingresando
       if (numero >= 48 && numero <= 57 || numero == 8){
       
       }else{
           evt.consume();
           JOptionPane.showMessageDialog(null, "Dato no valido");
       }
    }//GEN-LAST:event_txtPesoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxAbarrotes;
    private javax.swing.JComboBox<String> cbxCarnes;
    private javax.swing.JComboBox<String> cbxCarnesFrias;
    private javax.swing.JComboBox<String> cbxCategorias;
    private javax.swing.JComboBox<String> cbxDescuentos;
    private javax.swing.JComboBox<String> cbxIva;
    private javax.swing.JComboBox<String> cbxUnidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lbnDescripcion;
    private javax.swing.JLabel lbnPresio;
    private javax.swing.JLabel lbnSubTotal;
    private javax.swing.JLabel lbnSubTotal1;
    private javax.swing.JLabel lbnTipo;
    private javax.swing.JLabel lbnUnidades;
    private javax.swing.JMenuItem mnuAAgregar;
    private javax.swing.JMenuItem mnuAComprar;
    private javax.swing.JMenuItem mnuASalir;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPresio;
    // End of variables declaration//GEN-END:variables
}
